service: reddit-slackbot
provider:
  name: aws
  runtime: python2.7
  stage: production
  region: us-east-1
  memorySize: 512
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:UpdateFunctionConfiguration"

      # This parameter can be calculated according to the region and the account ID
      Resource: "arn:aws:lambda:us-east-1:[account-id]:function:reddit-slackbot-production-runner"

functions:
  runner:
    handler: main.handler
    description: "Slackbot: Reddit Submissions"
    events:
      - schedule: rate(1 hour)
    environment:
      # Start time, e.g. the output of time.time()
      LAST_SUBMISSION: "1521756333.7"



